default: &default
  ahn_core_host: "localhost"
  ahn_core_username: "rayo@rayo.somleng.org"
  ahn_core_password: "secret"
  ahn_http_username: "adhearsion"
  ahn_http_password: "password"
  call_platform_host: "http://localhost:3000"
  call_platform_username: "services"
  call_platform_password: "password"

production:
  <<: *default
  sentry_dsn: "<%= AppSettings.credentials.fetch('sentry_dsn') %>"
  ahn_core_host: "freeswitch.somleng.org"
  ahn_core_password: "<%= AppSettings.credentials.fetch('ahn_core_password') %>"
  ahn_http_password: "<%= AppSettings.credentials.fetch('ahn_http_password') %>"
  call_platform_host: "https://twilreapi.somleng.org"
  call_platform_password: "<%= AppSettings.credentials.fetch('call_platform_password') %>"

development: &development
  <<: *default

test:
  <<: *development
